version: 0.2

phases:
  build:
    commands:
      - export PATH="${HOME}/.cargo/bin:${PATH}"
      - cargo version
      - make release

artifacts:
  files:
    - codebuild/**/*
    - output/**/*
    - docker/**/*